### ISSUE TITLE
Dead link on vninja.net

### ISSUE THREAD

**Issue by iootaa** [h0bbel/h0bbel#1] opened 2020-09-25 09:52 UTC
Hi there,

[A page on your blog]( https://vninja.net/2020/02/12/my-hugo-workflow/) contains a link pointing to "a few custom Hugo shortcodes for Bootstrap4". This link is 404

(not sure of the right place to reach you as I don't use Twitter anymore)

Cheers

**Comment by h0bbel** [comment] 2021-06-14 09:37
Seems to work for me, probably just a blip. Thanks for reporting though.

**Comment by iaeiou** [comment] 2021-09-30 21:11
The issue is still there, 404 on "a few custom Hugo shortcodes for Bootstrap4"

**Comment by h0bbel** [comment] 2021-10-28 10:06
Aha, that's because my source code is now in a private repository (no wonder it worked for me).

**Comment by h0bbel** [comment] 2021-10-28 10:38
Fixed now.

**Closed as completed by h0bbel** 2021-10-28 10:38 UTC
